version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command: -a 10 --deterministic

  blockchain-node:
    build: ./blockchain-node
    ports:
      - "8001:8001"
    depends_on:
      - ganache

  backend-api:
    build: ./backend-api
    ports:
      - "5000:5000"
    environment:
      - ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}
    depends_on:
      - ganache
      - blockchain-node

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
